@echo off
setlocal enabledelayedexpansion

title Agents-Opencode-Jake — Setup

:: --- Figure out where we are ---
set "SCRIPT_DIR=%~dp0"
set "TARGET_DIR=%CD%\"

echo ============================================
echo  Agents-Opencode-Jake — Install into project
echo ============================================
echo.
echo  Running from: %SCRIPT_DIR%
echo  Installing to: %TARGET_DIR%
echo.

:: --- Verify payload files are nearby ---
if not exist "%SCRIPT_DIR%AGENTS.md" (
    echo  [ERROR] AGENTS.md not found next to setup.bat.
    echo  Make sure setup.bat is in the dist/ folder or repo root.
    pause
    exit /b 1
)
if not exist "%SCRIPT_DIR%opencode.json" (
    echo  [ERROR] opencode.json not found next to setup.bat.
    pause
    exit /b 1
)

:: ---- Step 1: Check Python ----
echo [1/7] Checking Python...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo  [ERROR] Python not found. Please install Python 3.10+.
    pause
    exit /b 1
)
for /f "tokens=2" %%v in ('python --version 2^>^&1') do set "PY_VER=%%v"
echo  Python %PY_VER%
echo.

:: ---- Step 2: Install Python dependencies (only if missing) ----
:: Check each dependency via Python import. The pip distribution name for
:: graphify is `graphifyy` (typo-squat avoidance on PyPI) but the import
:: is `graphify`. We install only the missing ones; re-runs are a no-op.
echo [2/7] Checking Python dependencies...
set "MISSING_DEPS="
python -c "import graphify" >nul 2>&1
if %errorlevel% neq 0 set "MISSING_DEPS=!MISSING_DEPS! graphifyy"
python -c "import pytest" >nul 2>&1
if %errorlevel% neq 0 set "MISSING_DEPS=!MISSING_DEPS! pytest"
python -c "import jsonschema" >nul 2>&1
if %errorlevel% neq 0 set "MISSING_DEPS=!MISSING_DEPS! jsonschema"
if "!MISSING_DEPS!"=="" (
    echo  All dependencies already installed.
) else (
    echo  [INSTALL] missing:!MISSING_DEPS!
    pip install !MISSING_DEPS! 2>&1 | findstr /V "already satisfied" | findstr /V "^$"
)
echo.

:: ---- Step 3: Copy agent files into project ----
echo [3/7] Copying agent files...

:: AGENTS.md
copy /Y "%SCRIPT_DIR%AGENTS.md" "%TARGET_DIR%AGENTS.md" >nul
echo    AGENTS.md

:: scripts/
if not exist "%TARGET_DIR%scripts" mkdir "%TARGET_DIR%scripts"
if exist "%SCRIPT_DIR%scripts\verify-plan.py" (
    copy /Y "%SCRIPT_DIR%scripts\verify-plan.py" "%TARGET_DIR%scripts\verify-plan.py" >nul
    copy /Y "%SCRIPT_DIR%scripts\pre-commit" "%TARGET_DIR%scripts\pre-commit" >nul
    if exist "%SCRIPT_DIR%scripts\install-hook.sh" (
        copy /Y "%SCRIPT_DIR%scripts\install-hook.sh" "%TARGET_DIR%scripts\install-hook.sh" >nul
    )
    echo    scripts\ (verify-plan.py, pre-commit, install-hook.sh)
)

:: .opencode/skills/
if not exist "%TARGET_DIR%.opencode\skills\graphify-agent-workflow" (
    mkdir "%TARGET_DIR%.opencode\skills\graphify-agent-workflow"
)
if exist "%SCRIPT_DIR%.opencode\skills\graphify-agent-workflow\SKILL.md" (
    copy /Y "%SCRIPT_DIR%.opencode\skills\graphify-agent-workflow\SKILL.md" "%TARGET_DIR%.opencode\skills\graphify-agent-workflow\SKILL.md" >nul
    echo    .opencode\skills\graphify-agent-workflow\SKILL.md
)
echo.

:: ---- Step 4: Merge or create opencode.json ----
echo [4/7] Configuring opencode.json...

if exist "%TARGET_DIR%opencode.json" (
    echo  Project already has opencode.json — merging agent block...
    python -c "
import json, sys, io
src = json.load(open(r'%SCRIPT_DIR%opencode.json', encoding='utf-8'))
tgt_file = r'%TARGET_DIR%opencode.json'
tgt = json.load(open(tgt_file, encoding='utf-8'))
tgt['agent'] = src['agent']
tgt['instructions'] = list(set(tgt.get('instructions', []) + ['AGENTS.md']))
tgt.setdefault('skills', {})['paths'] = list(set(tgt.get('skills', {}).get('paths', []) + ['.opencode/skills']))
with open(tgt_file, 'w', encoding='utf-8') as f:
    json.dump(tgt, f, indent=2, ensure_ascii=False)
print('  Merged: agent block copied, instructions + skills paths added')
"
) else (
    echo  No opencode.json found — copying standalone config...
    copy /Y "%SCRIPT_DIR%opencode.json" "%TARGET_DIR%opencode.json" >nul
    echo  Created: opencode.json (standalone with all 13 agents)
)
echo.

:: ---- Step 5: Create .opencode structure ----
echo [5/7] Creating .opencode structure...
if not exist "%TARGET_DIR%.opencode\plans\completed" mkdir "%TARGET_DIR%.opencode\plans\completed"
if not exist "%TARGET_DIR%.opencode\decisions" mkdir "%TARGET_DIR%.opencode\decisions"
if not exist "%TARGET_DIR%.opencode\todo.md" type nul > "%TARGET_DIR%.opencode\todo.md"
if not exist "%TARGET_DIR%.opencode\work-log.md" (
    echo # Work Log > "%TARGET_DIR%.opencode\work-log.md"
    echo. >> "%TARGET_DIR%.opencode\work-log.md"
    echo Auto-generated by the conductor agent. >> "%TARGET_DIR%.opencode\work-log.md"
)
echo  .opencode structure ready.
echo.

:: ---- Step 6: Initialize git + ignore + hook ----
echo [6/7] Setting up git...
if not exist "%TARGET_DIR%.git" (
    git init
    echo  Git repository initialized.
) else (
    echo  Git repository already exists.
)
if not exist "%TARGET_DIR%.gitignore" (
    echo Creating .gitignore...
    (
        echo # Python
        echo __pycache__/
        echo *.pyc
        echo *.pyo
        echo *.egg-info/
        echo .eggs/
        echo dist/
        echo build/
        echo.
        echo # Node
        echo node_modules/
        echo .opencode/node_modules/
        echo.
        echo # opencode
        echo graphify-out/
        echo .opencode/plans/plan-*.md
        echo .opencode/reports/
        echo.
        echo # Environment
        echo .env
        echo .venv
        echo venv/
        echo.
        echo # OS
        echo Thumbs.db
        echo .DS_Store
        echo.
        echo # IDE
        echo .vscode/
        echo .idea/
        echo *.swp
        echo *.swo
    ) > "%TARGET_DIR%.gitignore"
    echo  .gitignore created.
) else (
    echo  .gitignore already exists.
)

:: Install pre-commit hook
if exist "%TARGET_DIR%scripts\pre-commit" (
    if exist "%TARGET_DIR%.git" (
        copy /Y "%TARGET_DIR%scripts\pre-commit" "%TARGET_DIR%.git\hooks\pre-commit" >nul 2>&1
        if !errorlevel! equ 0 (
            echo  Pre-commit hook installed.
        ) else (
            echo  [INFO] Could not install pre-commit hook.
        )
    )
)
echo.

:: ---- Step 7: Build knowledge graph ----
echo [7/7] Building knowledge graph...
python -m graphify "%TARGET_DIR%" --depth 5 --export html --export json 2>nul
if %errorlevel% equ 0 (
    echo  Knowledge graph built: graphify-out\
) else (
    echo  [INFO] Graph build skipped (graphify may not support --depth).
    echo  Run once opencode is open: /graphify .
)
echo.

:: ---- Summary ----
echo ============================================
echo  Setup complete!
echo ============================================
echo.
echo  Copied to: %TARGET_DIR%
echo.
echo  What was installed:
echo    - AGENTS.md  (agent workflow docs)
echo    - opencode.json  (13 agent definitions)
echo    - scripts\  (verify-plan.py, pre-commit hook)
echo    - .opencode\  (skills, plans, decisions, todo)
echo    - .gitignore
echo    - Pre-commit hook
echo    - Knowledge graph
echo.
echo  Now run: opencode .
echo  Then:    /graphify .
echo.
pause
