@echo off
setlocal enabledelayedexpansion

title Agents-Opencode-Jake — Local Setup

set "REPO_DIR=%~dp0"

echo ============================================
echo  Agents-Opencode-Jake — Local Project Setup
echo ============================================
echo.
echo  Repo: %REPO_DIR%
echo.

:: ---- Step 1: Check Python ----
echo [1/6] Checking Python...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo  [ERROR] Python not found. Please install Python 3.10+.
    pause
    exit /b 1
)
python --version
echo.

:: ---- Step 2: Install dependencies ----
echo [2/6] Installing Python dependencies...
pip install graphify pytest jsonschema 2>&1 | findstr /V "already satisfied" | findstr /V "^$"
echo.

:: ---- Step 3: Create .opencode structure ----
echo [3/6] Ensuring .opencode directory structure...
if not exist "%REPO_DIR%.opencode\plans\completed" mkdir "%REPO_DIR%.opencode\plans\completed"
if not exist "%REPO_DIR%.opencode\decisions" mkdir "%REPO_DIR%.opencode\decisions"
if not exist "%REPO_DIR%.opencode\todo.md" type nul > "%REPO_DIR%.opencode\todo.md"
if not exist "%REPO_DIR%.opencode\work-log.md" (
    echo # Work Log > "%REPO_DIR%.opencode\work-log.md"
    echo. >> "%REPO_DIR%.opencode\work-log.md"
    echo Auto-generated by the conductor agent. >> "%REPO_DIR%.opencode\work-log.md"
)
echo  .opencode structure ready.
echo.

:: ---- Step 4: Initialize git (if needed) ----
echo [4/6] Checking git repository...
if not exist "%REPO_DIR%.git" (
    git init
    echo  Git repository initialized.
) else (
    echo  Git repository already exists.
)
if not exist "%REPO_DIR%.gitignore" (
    echo Creating .gitignore...
    (
        echo # Python
        echo __pycache__/
        echo *.pyc
        echo *.pyo
        echo *.egg-info/
        echo .eggs/
        echo dist/
        echo build/
        echo.
        echo # Node
        echo node_modules/
        echo .opencode/node_modules/
        echo.
        echo # opencode
        echo graphify-out/
        echo .opencode/plans/plan-*.md
        echo .opencode/reports/
        echo.
        echo # Environment
        echo .env
        echo .venv
        echo venv/
        echo.
        echo # OS
        echo Thumbs.db
        echo .DS_Store
        echo.
        echo # IDE
        echo .vscode/
        echo .idea/
        echo *.swp
        echo *.swo
    ) > "%REPO_DIR%.gitignore"
    echo  .gitignore created.
) else (
    echo  .gitignore already exists.
)
echo.

:: ---- Step 5: Install pre-commit hook ----
echo [5/6] Installing pre-commit hook...
if exist "%REPO_DIR%scripts\install-hook.sh" (
    if exist "%REPO_DIR%.git" (
        bash "%REPO_DIR%scripts\install-hook.sh" 2>nul
        if !errorlevel! equ 0 (
            echo  Pre-commit hook installed.
        ) else (
            echo  [INFO] Could not install hook (bash may be unavailable).
            echo  Manual: copy scripts\pre-commit to .git\hooks\pre-commit
        )
    )
) else (
    echo  [SKIP] scripts\install-hook.sh not found.
)
echo.

:: ---- Step 6: Build knowledge graph ----
echo [6/6] Building knowledge graph...
python -m graphify "%REPO_DIR%" --depth 5 --export html --export json 2>nul
if %errorlevel% equ 0 (
    echo  Knowledge graph built at: %REPO_DIR%graphify-out\
    echo.
    echo  Inspect: graphify-out/graph.html
) else (
    echo  [INFO] Knowledge graph build skipped (graphify may not support --depth).
    echo  Run this once opencode is open: /graphify .
)
echo.

echo ============================================
echo  Local setup complete!
echo ============================================
echo.
echo  Next steps:
echo    1. opencode .
echo    2. Run: /graphify .
echo    3. Run: /setup-project (if this is a new project)
echo.
pause
