@echo off
setlocal enabledelayedexpansion

title Agents-Opencode-Jake — Local Uninstall

:: --- Parse flags (args take precedence over env vars) ---
:: Accept %~1, %~2, %~3 as --unattended, --dry-run, --force. Env vars
:: UNINSTALL_YES, UNINSTALL_DRY_RUN, UNINSTALL_FORCE also work.
set "UNATTENDED="
set "DRY_RUN="
set "FORCE="

for %%A in ("%~1" "%~2" "%~3") do (
    if /i "%%~A"=="--unattended" set "UNATTENDED=1"
    if /i "%%~A"=="--dry-run"   set "DRY_RUN=1"
    if /i "%%~A"=="--force"     set "FORCE=1"
)

if "%UNINSTALL_YES%"=="1"      set "UNATTENDED=1"
if "%UNINSTALL_DRY_RUN%"=="1"  set "DRY_RUN=1"
if "%UNINSTALL_FORCE%"=="1"    set "FORCE=1"
:: --unattended implies --force (skip all prompts)
if "%UNATTENDED%"=="1"         set "FORCE=1"

set "REPO_DIR=%~dp0"

echo ============================================
echo  Agents-Opencode-Jake -- Local Uninstall
echo ============================================
echo.
echo  Repo: %REPO_DIR%
echo.
echo  This will remove local project setup from this repo only.
echo  It will NOT affect other projects or global config.
if "%DRY_RUN%"=="1" echo  [DRY-RUN] no files will be removed.
if "%FORCE%"=="1"   echo  [FORCE]   skipping confirmations.
echo.

:: --- Confirmation prompt (skip when --unattended) ---
if "%UNATTENDED%"=="1" goto :unattended_confirm
call :prompt_confirm "Continue with local uninstall"
if errorlevel 1 (
    echo  Aborted.
    pause
    exit /b 0
)
echo.
:unattended_confirm
if "%UNATTENDED%"=="1" echo  [UNATTENDED] proceeding without prompt.
echo.

:: ---- Step 1: Remove pre-commit hook ----
echo [1/4] Removing pre-commit hook...
if not exist "%REPO_DIR%.git\hooks\pre-commit" goto :step1_skip
if "%DRY_RUN%"=="1" (
    echo  [DRY-RUN] would remove: .git\hooks\pre-commit
    goto :step1_done
)
del "%REPO_DIR%.git\hooks\pre-commit"
echo  Removed: .git\hooks\pre-commit
:step1_done
:step1_skip
echo.

:: ---- Step 2: Clean .opencode structure ----
echo [2/4] Cleaning .opencode structure...
echo.
echo  The following can be regenerated by running setup.bat again.
echo.
if "%FORCE%"=="1" (
    set "REMOVE_OPCODE=y"
    echo  [FORCE] removing .opencode/ without prompt.
    goto :step2_do_remove
)
call :prompt_yn "Remove .opencode/ directory (plans, decisions, work-log)"
if errorlevel 1 goto :step2_done
:step2_do_remove

call :remove_dir "%REPO_DIR%.opencode\agents" ".opencode\agents\"
call :remove_dir "%REPO_DIR%.opencode\plans" ".opencode\plans\"
call :remove_dir "%REPO_DIR%.opencode\decisions" ".opencode\decisions\"
call :remove_dir "%REPO_DIR%.opencode\reports" ".opencode\reports\"
call :remove_file "%REPO_DIR%.opencode\todo.md" ".opencode\todo.md"
call :remove_file "%REPO_DIR%.opencode\work-log.md" ".opencode\work-log.md"

:step2_done
echo.

:: ---- Step 3: Remove graphify-out ----
echo [3/4] Removing graphify-out (knowledge graph cache)...
if "%FORCE%"=="1" (
    set "REMOVE_GRAPH=y"
    echo  [FORCE] removing graphify-out/ without prompt.
    goto :step3_do_remove
)
call :prompt_yn "Remove graphify-out/ directory"
if errorlevel 1 goto :step3_skip
:step3_do_remove
call :remove_dir "%REPO_DIR%graphify-out" "graphify-out\"
:step3_skip
echo.

:: ---- Step 4: Optionally uninstall Python packages ----
echo [4/4] Python packages...
if "%FORCE%"=="1" (
    set "UNINSTALL_PIP=y"
    echo  [FORCE] uninstalling Python packages without prompt.
    goto :step4_do_remove
)
call :prompt_yn "Uninstall graphify, pytest, jsonschema"
if errorlevel 1 goto :step4_skip
:step4_do_remove
if "%DRY_RUN%"=="1" (
    echo  [DRY-RUN] would uninstall: graphify, pytest, jsonschema
    goto :step4_done
)
echo  Uninstalling graphify...
pip uninstall graphify -y >nul 2>&1
echo  Uninstalling pytest...
pip uninstall pytest -y >nul 2>&1
echo  Uninstalling jsonschema...
pip uninstall jsonschema -y >nul 2>&1
echo  Python packages uninstalled.
:step4_done
:step4_skip
echo.

echo ============================================
echo  Local uninstall complete!
echo ============================================
echo.
echo  Remaining (not removed):
echo    - .gitignore
echo    - Git repository
echo    - Python packages (if you chose to keep them)
echo.
echo  To reinstall later, run: setup.bat
echo.
pause
exit /b 0

:: ---- Helper: prompt for yes/no (returns errorlevel 0 for yes, 1 for no) ----
:prompt_yn
setlocal
set "PROMPT_TEXT=%~1? (y/N): "
set /p "RESPONSE=%PROMPT_TEXT%"
if /i "!RESPONSE!"=="y" (
    endlocal & exit /b 0
) else (
    endlocal & exit /b 1
)
goto :eof

:: ---- Helper: prompt for confirmation (returns errorlevel 0 for yes, 1 for no) ----
:prompt_confirm
setlocal
set "PROMPT_TEXT=%~1? (y/N): "
set /p "RESPONSE=%PROMPT_TEXT%"
if /i "!RESPONSE!"=="y" (
    endlocal & exit /b 0
) else (
    endlocal & exit /b 1
)
goto :eof

:: ---- Helper: remove directory ----
:remove_dir
if not exist "%~1" goto :eof
if "%DRY_RUN%"=="1" (
    echo  [DRY-RUN] would remove: %~2
    goto :eof
)
rmdir /S /Q "%~1"
echo  Removed: %~2
goto :eof

:: ---- Helper: remove file ----
:remove_file
if not exist "%~1" goto :eof
if "%DRY_RUN%"=="1" (
    echo  [DRY-RUN] would remove: %~2
    goto :eof
)
del "%~1"
echo  Removed: %~2
goto :eof
