#!/usr/bin/env python3
"""Build a self-contained agent bundle for use in any project.

The bundled files in ``dist/agents/`` are fully self-contained:
every ``{file:...}`` reference has been inlined with the referenced
content. Copy a single bundled .md to another project and the agent
works — no need for the source repo layout, no need for the
``shared/`` directory, no need for the include resolver.

This is the "agents work in any project" contract. See
``.opencode/plans/plan-002-any-project-portability.md`` for the
specification and rationale.

Usage:
    python scripts/build-self-contained-bundle.py

Output:
    dist/agents/{conductor,builder,...}.md    # 13 self-contained agents
    dist/agents/MANIFEST.md                   # coverage + size info
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path


# Make the resolve_includes module importable.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / ".opencode" / "scripts"))

from resolve_includes import resolve_text  # noqa: E402


# The 13 agent files we bundle. Order matters for the manifest.
AGENT_FILES = [
    "conductor.md", "planner.md",
    "builder.md", "architect.md", "reviewer.md", "tester.md",
    "docs.md", "debugger.md", "refactor.md",
    "git.md", "explorer.md", "security.md", "perf.md",
]

# Where the source lives and where the bundle is written.
AGENTS_SRC = REPO_ROOT / ".opencode" / "agents"
BUNDLE_DIR = REPO_ROOT / "dist" / "agents"

# Same regex the resolve_includes module uses (kept here for coverage analysis).
FILE_REF = re.compile(r"\{file:([^}]+)\}")


def _count_unresolved(text: str) -> list[str]:
    """Return the list of unresolved {file:...} references in the text."""
    return FILE_REF.findall(text)


def _gather_includes(text: str) -> set[str]:
    """Return the set of distinct {file:...} references in the text."""
    return set(FILE_REF.findall(text))


def build_bundle() -> dict[str, dict]:
    """Resolve all agent .md files into the bundle directory.

    Returns a dict mapping agent filename -> dict with:
        - "source_size": bytes in source file
        - "bundled_size": bytes after inlining
        - "includes": list of distinct {file:} refs that were inlined
        - "unresolved": list of {file:} refs that could not be inlined
    """
    BUNDLE_DIR.mkdir(parents=True, exist_ok=True)
    report: dict[str, dict] = {}

    for name in AGENT_FILES:
        src = AGENTS_SRC / name
        if not src.exists():
            report[name] = {
                "source_size": 0,
                "bundled_size": 0,
                "includes": [],
                "unresolved": [f"<missing source: {src}>"],
            }
            continue

        text = src.read_text(encoding="utf-8")
        includes = sorted(_gather_includes(text))
        # Resolve transitively (resolve_text is recursive).
        resolved = resolve_text(text, REPO_ROOT)
        unresolved = _count_unresolved(resolved)

        bundled = BUNDLE_DIR / name
        bundled.write_text(resolved, encoding="utf-8")

        report[name] = {
            "source_size": src.stat().st_size,
            "bundled_size": len(resolved.encode("utf-8")),
            "includes": includes,
            "unresolved": unresolved,
        }

    return report


def write_manifest(report: dict[str, dict]) -> None:
    """Write dist/agents/MANIFEST.md describing the bundle.

    The manifest documents:
    - When the bundle was built
    - Which agent files are in the bundle
    - Which shared files were inlined into which agents
    - Which references (if any) couldn't be resolved
    - How to use the bundle in another project
    """
    total_source = sum(r["source_size"] for r in report.values())
    total_bundled = sum(r["bundled_size"] for r in report.values())

    # Reverse index: which agents include which shared file
    shared_to_agents: dict[str, list[str]] = {}
    for agent_name, info in report.items():
        for ref in info["includes"]:
            shared_to_agents.setdefault(ref, []).append(agent_name)

    lines: list[str] = []
    lines.append("# Self-Contained Agent Bundle")
    lines.append("")
    lines.append("Auto-generated by `scripts/build-self-contained-bundle.py`.")
    lines.append("Each `.md` file in this directory is **fully self-contained**:")
    lines.append("all `{file:...}` references have been inlined. Copy a single file")
    lines.append("to another project and the agent works — no need for the source")
    lines.append("repo layout, no need for the `shared/` directory, no need for the")
    lines.append("include resolver.")
    lines.append("")
    lines.append("## Use in any project")
    lines.append("")
    lines.append("```bash")
    lines.append("# Copy one or more agents to your target project")
    lines.append("cp dist/agents/conductor.md /path/to/your/project/.opencode/agents/")
    lines.append("cp dist/agents/builder.md    /path/to/your/project/.opencode/agents/")
    lines.append("# ... etc.")
    lines.append("```")
    lines.append("")
    lines.append("Or copy the whole bundle:")
    lines.append("")
    lines.append("```bash")
    lines.append("cp -r dist/agents/* /path/to/your/project/.opencode/agents/")
    lines.append("```")
    lines.append("")
    lines.append("The agent will announce its operating mode (dispatch or single-agent)")
    lines.append("on the first response based on whether the env exposes a `task` tool.")
    lines.append("")
    lines.append("## Bundle contents")
    lines.append("")
    lines.append(f"- Built at: {datetime.now(timezone.utc).isoformat()}")
    lines.append(f"- Agents: {len(report)}")
    lines.append(f"- Source size: {total_source:,} bytes")
    lines.append(f"- Bundled size: {total_bundled:,} bytes")
    lines.append(f"- Growth from inlining: {total_bundled - total_source:,} bytes "
                 f"({(total_bundled / total_source - 1) * 100:.1f}%)"
                 if total_source else "")
    lines.append("")

    # Per-agent table
    lines.append("## Per-agent")
    lines.append("")
    lines.append("| Agent | Source | Bundled | Includes inlined | Unresolved |")
    lines.append("|---|---:|---:|---:|---:|")
    for name in AGENT_FILES:
        info = report.get(name, {})
        if not info:
            continue
        src_size = info["source_size"]
        bnd_size = info["bundled_size"]
        n_in = len(info["includes"])
        n_un = len(info["unresolved"])
        marker = " [WARN]" if n_un else ""
        lines.append(f"| {name}{marker} | {src_size:,} | {bnd_size:,} | "
                     f"{n_in} | {n_un} |")
    lines.append("")

    # Reverse index: shared -> agents that use it
    if shared_to_agents:
        lines.append("## Shared files inlined")
        lines.append("")
        lines.append("The `{file:...}` references below were resolved into the agent")
        lines.append("files. The agents are now self-contained and do not depend on the")
        lines.append("source repo's `shared/` directory.")
        lines.append("")
        lines.append("| Shared file | Inlined into |")
        lines.append("|---|---|")
        for ref in sorted(shared_to_agents.keys()):
            agents = sorted(shared_to_agents[ref])
            agents_str = ", ".join(f"`{a}`" for a in agents)
            lines.append(f"| `{ref}` | {agents_str} |")
        lines.append("")

    # Any unresolved references (should be zero in a healthy build)
    unresolved_total = sum(len(r["unresolved"]) for r in report.values())
    if unresolved_total:
        lines.append("## Unresolved references (action required)")
        lines.append("")
        lines.append("The following `{file:...}` references could not be resolved.")
        lines.append("Agents with unresolved references will not work in projects that")
        lines.append("lack the source repo layout. Investigate the missing files.")
        lines.append("")
        for name, info in report.items():
            for ref in info["unresolved"]:
                lines.append(f"- `{name}` -> `{ref}`")
        lines.append("")

    (BUNDLE_DIR / "MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    print("Building self-contained agent bundle...")
    report = build_bundle()
    write_manifest(report)
    unresolved = sum(len(r["unresolved"]) for r in report.values())
    bundled_count = sum(1 for r in report.values() if r["bundled_size"] > 0)
    print(f"  Wrote {bundled_count} agent file(s) to {BUNDLE_DIR}")
    print(f"  Wrote MANIFEST.md to {BUNDLE_DIR}")
    if unresolved:
        print(f"  [WARN] {unresolved} unresolved {{file:...}} reference(s). "
              f"See MANIFEST.md for details.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
